# Generated by Django 5.2.5 on 2025-09-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_remove_product_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
