# Generated by Django 5.2.5 on 2025-09-05 12:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
