# Generated by Django 5.2.5 on 2025-09-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="capacity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="origin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="skin_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
