# Generated by Django 5.2.5 on 2025-09-08 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_product_capacity_product_ingredients_product_origin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="store.discountcode",
            ),
        ),
    ]
