# Generated by Django 5.2.5 on 2025-09-08 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_cart_discount_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="discount_code",
        ),
    ]
