# Generated by Django 5.2.5 on 2025-09-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_remove_cart_discount_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceFeeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percent",
                    models.FloatField(default=2.0, help_text="Phần trăm phí dịch vụ"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="shipping_address",
            field=models.CharField(
                blank=True,
                help_text="Địa chỉ giao hàng của giỏ hàng",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_shipping_address",
            field=models.CharField(
                blank=True,
                help_text="Địa chỉ giao hàng mặc định",
                max_length=255,
                null=True,
            ),
        ),
    ]
