# Generated by Django 5.2.5 on 2025-09-09 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_servicefeeconfig_cart_shipping_address_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceFeeConfig",
            new_name="ServiceFee",
        ),
    ]
