# Generated by Django 5.2.5 on 2025-09-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_cart_discount_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="service_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="cart",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
