# Generated by Django 5.2.5 on 2025-09-11 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_useraddress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="shipping_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="shipping_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="default_shipping_address",
            new_name="address",
        ),
    ]
