# Generated by Django 5.2.5 on 2025-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_rename_shipping_address_cart_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
